# -*- coding: utf-8 -*-
"""food_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYRzH9wbTB-oNOwweU-kxc_ptZCNPu6v
"""
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver
from langgraph.store.memory import InMemoryStore
from state import State
from nodes import chat_model, write_memory, summarization_node
from langchain_core.messages import HumanMessage


builder = StateGraph(State)
builder.add_node(chat_model)
builder.add_node(write_memory)
builder.add_node(summarization_node)

builder.add_edge(START, 'chat_model')
builder.add_edge('chat_model', 'write_memory')
builder.add_edge('chat_model', 'summarization_node')
builder.add_edge('summarization_node', END)

across_thread = MemorySaver()
store = InMemoryStore()

graph = builder.compile(checkpointer=across_thread, store=store)
graph